### ISSUE TITLE
SceneGraph Build error 

### ISSUE THREAD

**Issue by hamsal** [ankurhanda/SceneNetv1.0#1]
I'm trying to build and I get the following error message when I run 
`cmake .. -DCUDA_PROPAGATE_HOST_FLAGS=0`

CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindSceneGraph.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "SceneGraph", but CMake did not find one.

  Could not find a package configuration file provided by "SceneGraph" with
  any of the following names:

   SceneGraphConfig.cmake
   scenegraph-config.cmake

  Add the installation prefix of "SceneGraph" to CMAKE_PREFIX_PATH or set
  "SceneGraph_DIR" to a directory containing one of the above files.  If
  "SceneGraph" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by ankurhanda** [comment]
oh sorry, it is here https://github.com/ankurhanda/SceneGraphRendering. Does that help?
