### ISSUE TITLE
povray_utils::generate_POVRay_commands function not provided

### ISSUE THREAD

**Issue by howard-mahe** [ankurhanda/SceneNetv1.0#2]
Hi,

I successfully compiled all dependencies, after modifying all Pangolin includes (as mentionned in ankurhanda/SceneGraphRendering#1).

But I can't build _main_living_room_dynamic.cpp_ because the last line call the function 'generate_POVRay_commands' which isn't provided in povray_utils.h (or anywhere else).

**Comment by ankurhanda** [comment]
just commented out that command and updated it in the repo - you don't need it! Sorry, need to clean up code at places

**Comment by howard-mahe** [comment]
Good. thank you!
