### ISSUE TITLE
class mappings

### ISSUE THREAD

**Issue by nlgranger** [ankurhanda/SceneNetv1.0#5]
The class mapping link for NYUv2 is dead. I wasn't able to find the 13 class mapping on the page of the referenced paper either.
By any chance, could you please upload these mapping somewhere?

**Comment by ankurhanda** [comment]
I put the .mat files that have the mappings here https://github.com/ankurhanda/nyuv2-meta-data

**Comment by nlgranger** [comment]
Sorry, I had not noticed this repo. Thank you very much!

**Comment by nlgranger** [comment]
Closing
