### ISSUE TITLE
Broken link in README: Relevant Documents

### ISSUE THREAD

**Issue by sebastianfeistl** [ankurhanda/SceneNetv1.0#6]
I would like to draw your attention to the README link for "_SceneNet: an Annotated Model Generator for Indoor Scene Understanding_" which refers to a website that (I assume) was hacked and does not show the SceneNet document but instead some inappropriate content.

Please remove the current link and I would appreciate it if you could replace it with the actual document. Thank you!

**Comment by ankurhanda** [comment]
Thanks for bringing this up and I have updated it.

**Comment by sebastianfeistl** [comment]
Thank you for the quick response!
