### ISSUE TITLE
Changed access rights to the scenenet dataset

### ISSUE THREAD

**Issue by themasterlink** [ankurhanda/SceneNetv1.0#7]
Hey,

thank you so much for this dataset! Would it be possible to change the access rights of the SceneNet dataset under the following link: http://tinyurl.com/zpc9ppb back to public?

Best,
Max

**Comment by ankurhanda** [comment]
Can you try this again https://drive.google.com/file/d/0B_CLZMBI0zcuQ3ZMVnp1RUkyOFk/view?usp=sharing&resourcekey=0-w8JN2r3WQ48eZltxQ-fSwA

Please let me know if this still doesn't work.

**Comment by themasterlink** [comment]
Hey,

that works! Thank you so much!

We will update that in the BlenderProc repo, maybe you can add the improved link also to the readme here?

Best,
Max
